FROM php:8.3-apache

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libpq-dev \
    && docker-php-ext-install \
        pgsql \
        pdo_pgsql \
    && rm -rf /var/lib/apt/lists/*

RUN a2enmod headers

WORKDIR /var/www/html